import { Brain, Target, TrendingUp, AlertTriangle, Zap } from "lucide-react";

/**
 * AIInsight - AI Intelligence Brief panel (Zenith style: minimal)
 */
export default function AIInsight({ insights, modelVersion, generatedAt }) {
  const iconMap = {
    prospectivity: { icon: Target, color: "text-zenith-accent", bg: "bg-zenith-accent/10", border: "border-zenith-accent/20" },
    production: { icon: TrendingUp, color: "text-white", bg: "bg-zenith-surface", border: "border-zenith-border" },
    risk: { icon: AlertTriangle, color: "text-red-400", bg: "bg-red-500/10", border: "border-red-500/20" },
    operational: { icon: Zap, color: "text-text-secondary", bg: "bg-zenith-surface", border: "border-zenith-border" },
  };

  const formatDate = (isoString) => {
    const date = new Date(isoString);
    return date.toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <section className="relative bg-zenith-elevated/80 backdrop-blur-xl rounded-xl p-6 lg:p-8 border border-zenith-border overflow-hidden">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
        <div className="flex items-center gap-4">
          <div className="p-3 rounded-lg bg-zenith-accent/10 border border-zenith-accent/20">
            <Brain className="w-6 h-6 text-zenith-accent" aria-hidden="true" />
          </div>
          <div>
            <h2 className="font-display font-semibold text-white text-xl mb-1">AI Intelligence Brief</h2>
            <p className="text-xs text-text-muted">
              Generated by <span className="font-mono text-white">{modelVersion}</span> · {formatDate(generatedAt)}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="px-3 py-1.5 rounded-full bg-green-500/10 border border-green-500/20 text-green-400 text-xs font-medium uppercase tracking-wider flex items-center gap-1.5">
            <span className="relative flex h-1.5 w-1.5">
              <span className="animate-ping absolute inset-0 rounded-full bg-green-500 opacity-75" />
              <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-green-500" />
            </span>
            Live
          </span>
          <div className="px-3 py-1.5 rounded-full bg-zenith-accent/10 border border-zenith-accent/20 text-zenith-accent text-xs font-medium font-mono">
            Confidence: {Math.round(insights.reduce((sum, i) => sum + i.confidence, 0) / insights.length * 100)}%
          </div>
        </div>
      </div>

      {/* Insights - minimal cards */}
      <div className="space-y-3" role="list" aria-label="AI insights">
        {insights.map((insight, index) => {
          const iconConfig = iconMap[insight.type] || iconMap.operational;
          const Icon = iconConfig.icon;

          return (
            <article
              key={insight.id}
              className={`relative group bg-zenith-surface/50 rounded-lg p-5 border ${iconConfig.border} transition-all duration-200 hover:border-zenith-border/50`}
              role="listitem"
              style={{ animationDelay: `${index * 80}ms` }}
            >
              <div className="flex gap-4">
                <div className={`p-2.5 rounded-lg ${iconConfig.bg} ${iconConfig.border} flex-shrink-0 relative`}>
                  <Icon className={`w-5 h-5 ${iconConfig.color}`} aria-hidden="true" />
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-4 mb-2">
                    <h3 className="font-display font-medium text-white text-base leading-snug pr-4">{insight.title}</h3>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <span className="px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider"
                        style={{
                          background: `rgba(229, 57, 53, 0.1)`,
                          color: "#e53935",
                          border: `1px solid rgba(229, 57, 53, 0.2)`,
                        }}
                      >
                        {insight.type}
                      </span>
                      <div className="flex items-center gap-1.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-zenith-accent" />
                        <span className="text-xs font-mono text-text-secondary">
                          {Math.round(insight.confidence * 100)}%
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <p className="text-text-secondary text-sm leading-relaxed">{insight.content}</p>
                </div>
              </div>
            </article>
          );
        })}
      </div>

      {/* Disclaimer - minimal */}
      <div className="mt-8 pt-6 border-t border-zenith-border">
        <p className="text-xs text-text-muted flex items-center gap-2">
          <span className="w-3.5 h-3.5 text-text-subtle">◆</span>
          <span>This brief contains AI-generated insights based on model predictions. 
          <strong className="text-text-secondary">Content is mock/dynamic</strong> and structured for future ML output integration.</span>
        </p>
      </div>
    </section>
  );
}